# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: home
  url: /
  icon:
- page: åç«¯
  url: /categories/åç«¯/
  icon:
- page: Linux
  url: /categories/Linux/
  icon:
- page: å­˜å‚¨
  url: /categories/å­˜å‚¨/
  icon:
- page: é¢è¯•
  url: /categories/é¢è¯•/
  icon:
- page: å·¥å…·
  url: /categories/å·¥å…·/
  icon:
- page: å…¶ä»–
  url: /categories/å…¶ä»–/
  icon:
- page: æ—¶é—´è½´
  url: /archives/
  icon:

## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: img/head-img.jpg

# å„ä¸ªå°å·¥å…·çš„è®¾ç½®

## widgets
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends

## æœç´¢
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## ç½‘ç«™å…¬å‘Šè®¾ç½®
notification: |-
            <p>
            æ¬¢è¿å…‰ä¸´ Binchen Coder æŠ€æœ¯åšå®¢ ğŸ¤ğŸ¤ğŸ¤ <br/>
            <hr/>
            <p style="color: #e67e22; background-image: -webkit-linear-gradient(left, #cddc39, #e67e22 25%, #cddc39 50%, #e67e22 75%, #cddc39) !important; -webkit-text-fill-color: transparent!important; -webkit-background-clip:text!important; background-size: 200% 100%!important; animation: masked-animation 2s infinite linear !important;">
            é¢å¯¹è¿‡å»æ— æ€¨æ— æ‚”ï¼ŒæŠŠæ¡ç°åœ¨å……æ»¡ä¿¡å¿ƒï¼Œå¤‡æˆ˜æœªæ¥æ— æ‰€ç•æƒ§ã€‚ä¿æŒä¿¡å¿µï¼Œå…‹æœææƒ§ï¼ä¸€ç‚¹ä¸€æ»´çš„ç§¯ç´¯ï¼Œä¸€ç‚¹ä¸€æ»´çš„æ²‰æ·€ã€‚
            </p>
            <strong style="color: #e67e22; font-size: 16px;">å­¦æŠ€æœ¯éœ€è¦ä¸æ–­çš„ç§¯æ·€ï¼</strong>
            </p>

## ç¤¾äº¤è®¾ç½®
social:
 - name: Github
   icon: git
   href: //github.com/binchencoder
 - name: é‚®ç®±
   icon: envelope-o
   href: mailto:c1325791024@163.com
 - name: è”ç³»QQ
   icon: qq
   href: /
 - name: å¾®ä¿¡
   icon: weixin
   href: /
 - name: QQç¾¤
   icon: users
   href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## æ–‡ç« åˆ†ç±»è®¾ç½®
cate_config:
   show_count: true
   show_current: true

## æ–‡ç« å½’æ¡£è®¾ç½®
arch_config:
   type: 'monthly'
   show_count: true
   order: -1

## å‹é“¾è®¾ç½®
links:
  - ä¸ªäººåšå®¢: https://binchencoder.github.io/


# ä¸»é¢˜è‡ªå®šä¹‰ä¸ªæ€§åŒ–é…ç½®

## ç½‘ç«™å®£ä¼ è¯­
branding: å¤œæ™šçš„ç¯å¡”ä¸€ç›´éƒ½åœ¨ï¼Œåªæ˜¯ç¯äº®çš„æ—¶å€™ï¼Œä½ æ‰çœ‹è§å®ƒ

## è®¾ç½®bannerèƒŒæ™¯å›¾ç‰‡
banner:
    img: /img/banner.jpg

## é¦–é¡µåˆ—è¡¨åº•éƒ¨é¢æ¿
homePanel: true

## ç¼©ç•¥å›¾è‡ªå®šä¹‰éšæœºå›¾ç‰‡
defaultImgs:
  -

## æˆªå–æ–‡ç« é¦–é¡µæè¿°å­—æ•°
excerptLength: 120

## æ˜¯å¦å¼€å¯æ–‡ç« ç›®å½•
toc: true

## ä»£ç é«˜äº®é…ç½®
highlightTheme:

## bootstrapé…ç½®
bootstrap:

## ICONé…ç½®
fontAwesome:

## æ–‡ç« è¿‡æœŸæé†’åŠŸèƒ½
warning:
  days: 1000
  text: 'æœ¬æ–‡äº%då¤©ä¹‹å‰å‘è¡¨ï¼Œæ–‡ä¸­å†…å®¹å¯èƒ½å·²ç»è¿‡æ—¶ã€‚'

## æ–‡ç« å†…å£°æ˜
declaration:
  enable: true
  title: 'è½¬è½½å£°æ˜'
  tip: |-
      å•†ä¸šè½¬è½½è¯·è”ç³»ä½œè€…è·å¾—æˆæƒ,éå•†ä¸šè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ Â© <a href="https://binchencoder.github.io/" target="_blank">Binchencoder</a>


## ä¸»é¢˜è¯„è®º

### gitment
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### æ¥å¿…åŠ›
livere:
  enable: true
  livere_uid: MTAyMC8zODI1Ny8xNDc4NQ

### å‹è¨€è¯„è®º(æœåŠ¡ä¸ç¨³å®š)
uyan:
  enable: false
  uyan_id: 1966422

### Disqusè¯„è®º
disqus:
  enable: false
  shortname: snippet
  count: false

### ç•…è¨€è¯„è®º(éœ€è¦ICPå¤‡æ¡ˆ)
changyan:
  enable: false
  appid:
  conf:

## Valineè¯„è®º
valine:
   enable: false
   appId: xOKV9J4UeQAtVkvnJC7Kq2Jn-gzGzoHsz
   appKey: erIpQac4azoCmgfBB7Dl9maa
   placeholder: è¯´ç‚¹ä»€ä¹ˆå§
   notify: false
   verify: false
   avatar: mm
   meta: nick,mail
   pageSize: 10

## ç½‘ç«™è®¿é—®ç»Ÿè®¡

### ç½‘ç›ŸCNZZç»Ÿè®¡
cnzz_analytics: 1263868967

### ç™¾åº¦ç»Ÿè®¡
baidu_analytics:

### è°·æ­Œç»Ÿè®¡
google_analytics:

### è…¾è®¯åˆ†æ
tencent_analytics:

### ç™¾åº¦æ–‡ç« æ¨é€
baidu_push:

#ç½‘ç«™ä¸»é¢˜é…ç½®
since: 2017
robot: 'all' ### æ§åˆ¶æœç´¢å¼•æ“çš„æŠ“å–å’Œç´¢å¼•ç¼–åˆ¶è¡Œä¸ºï¼Œé»˜è®¤ä¸ºall
version: 1.2.1
