# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: home
  url: /
  icon:
- page: åç«¯
  url: /categories/åç«¯/
  icon:
- page: Linux
  url: /categories/Linux/
  icon:
- page: å­˜å‚¨
  url: /categories/å­˜å‚¨/
  icon:
- page: é¢è¯•
  url: /categories/é¢è¯•/
  icon:
- page: å·¥å…·
  url: /categories/å·¥å…·/
  icon:
- page: å…¶ä»–
  url: /categories/å…¶ä»–/
  icon:
- page: æ—¶é—´è½´
  url: /archives/
  icon:

## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: img/head-img.jpg
  url: 'javascript:'

# å„ä¸ªå°å·¥å…·çš„è®¾ç½®

## widgets
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends

## æœç´¢
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## ç½‘ç«™å…¬å‘Šè®¾ç½®
notification: |-
            <p>
            æ¬¢è¿å…‰ä¸´ Binchen Coder æŠ€æœ¯åšå®¢ ğŸ¤ğŸ¤ğŸ¤ <br/>
            <hr/>
            <p style="color: #e67e22; background-image: -webkit-linear-gradient(left, #cddc39, #e67e22 25%, #cddc39 50%, #e67e22 75%, #cddc39) !important; -webkit-text-fill-color: transparent!important; -webkit-background-clip:text!important; background-size: 200% 100%!important; animation: masked-animation 2s infinite linear !important;">
            é¢å¯¹è¿‡å»æ— æ€¨æ— æ‚”ï¼ŒæŠŠæ¡ç°åœ¨å……æ»¡ä¿¡å¿ƒï¼Œå¤‡æˆ˜æœªæ¥æ— æ‰€ç•æƒ§ã€‚ä¿æŒä¿¡å¿µï¼Œå…‹æœææƒ§ï¼ä¸€ç‚¹ä¸€æ»´çš„ç§¯ç´¯ï¼Œä¸€ç‚¹ä¸€æ»´çš„æ²‰æ·€ã€‚
            </p>
            <strong style="color: #e67e22; font-size: 16px;">å­¦æŠ€æœ¯éœ€è¦ä¸æ–­çš„ç§¯æ·€ï¼</strong>
            </p>

## ç¤¾äº¤è®¾ç½®{@name:ç¤¾äº¤å·¥å…·åå­—ï¼Œ@icon:ç¤¾äº¤å·¥å…·å›¾æ ‡ï¼Œ@href:è®¾ç½®å·¥å…·é“¾æ¥} [å‚è€ƒå›¾æ ‡](http://fontawesome.io/icons/)
social:
 - name: Github
   icon: git
   href: //github.com/binchencoder
 - name: é‚®ç®±
   icon: envelope-o
   href: mailto:c1325791024@163.com
 - name: è”ç³»QQ
   icon: qq
   href: /
 - name: å¾®ä¿¡
   icon: weixin
   href: /
 - name: QQç¾¤
   icon: users
   href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## æ–‡ç« åˆ†ç±»è®¾ç½®
cate_config:
   show_count: true
   show_current: true

## æ–‡ç« å½’æ¡£è®¾ç½®
arch_config:
   type: 'monthly'
   format: 'YYYYå¹´MMæœˆ'
   show_count: true
   order: -1

## æ ‡ç­¾äº‘è®¾ç½®{/*å‚æ•°å‚è€ƒï¼šhttp://www.goat1000.com/tagcanvas-options.php */}
tagcloud:
  tag3d: false
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## å‹é“¾è®¾ç½®
links:
  - ä¸ªäººåšå®¢: https://binchencoder.github.io/


# ä¸»é¢˜è‡ªå®šä¹‰ä¸ªæ€§åŒ–é…ç½®

## ç½‘ç«™å®£ä¼ è¯­
branding: å¤œæ™šçš„ç¯å¡”ä¸€ç›´éƒ½åœ¨ï¼Œåªæ˜¯ç¯äº®çš„æ—¶å€™ï¼Œä½ æ‰çœ‹è§å®ƒ

## è®¾ç½®bannerèƒŒæ™¯å›¾ç‰‡
banner:
    img: /img/banner.jpg

## é¦–é¡µåˆ—è¡¨åº•éƒ¨é¢æ¿
homePanel: true

## é¦–é¡µæ–‡ç« åˆ—è¡¨ç¼©ç•¥å›¾
### åŠ è½½è§„åˆ™: è‡ªå®šä¹‰æ–‡ç« ç¼©ç•¥å›¾(åœ¨Front-matterä¸­æ·»åŠ çš„'img'å­—æ®µ) > æ–‡ç« å†…çš„å›¾ç‰‡ > defaultImgs(éšæœºè·å–) > æ— å›¾æ¨¡å¼åˆ—è¡¨

## ç¼©ç•¥å›¾è‡ªå®šä¹‰éšæœºå›¾ç‰‡
defaultImgs:
  -

## æˆªå–æ–‡ç« é¦–é¡µæè¿°å­—æ•°
excerptLength: 120

## æ˜¯å¦å¼€å¯æ–‡ç« ç›®å½•
toc: true

## ä»£ç é«˜äº®é…ç½®
highlightTheme: default

## bootstrapé…ç½®
bootstrap:

## ICONé…ç½® (ä¸é…åˆ™å¯ç”¨æœ¬åœ°Font Icon)
fontAwesome:

## æ–‡ç« è¿‡æœŸæé†’åŠŸèƒ½
warning:
  days: 1000
  text: 'æœ¬æ–‡äº%då¤©ä¹‹å‰å‘è¡¨ï¼Œæ–‡ä¸­å†…å®¹å¯èƒ½å·²ç»è¿‡æ—¶ã€‚'

## æ–‡ç« å†…å£°æ˜
declaration:
  enable: true
  title: 'è½¬è½½å£°æ˜'
  tip: |-
      å•†ä¸šè½¬è½½è¯·è”ç³»ä½œè€…è·å¾—æˆæƒ,éå•†ä¸šè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ Â© <a href="https://binchencoder.github.io/" target="_blank">Binchencoder</a>

## æ–‡ç« æ‰“èµ{@reward: {alipay:æ”¯ä»˜å®æ‰“èµ,wepay:å¾®ä¿¡æ‰“èµ,tip:æ‰“èµæç¤ºè¯­; é“¾æ¥éƒ½ä¸ºç©º,å…³é—­æ‰“èµåŠŸèƒ½}}
reward:
  alipay: ''
  wepay: ''
  tip: èµèµæ˜¯ä¸è€æµæ°“çš„é¼“åŠ±

## ä¸»é¢˜è¯„è®º

### gitment
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  labels:
  perPage:
  maxCommentHeight:

### æ¥å¿…åŠ›(é»˜è®¤é€‰é¡¹)
livere:
  enable: true
  livere_uid: MTAyMC8zODI1Ny8xNDc4NQ

### å‹è¨€è¯„è®º(æœåŠ¡ä¸ç¨³å®šï¼Œç»å¸¸æ— æ³•åŠ è½½)
uyan:
  enable: false
  uyan_id: 1966422

### Disqusè¯„è®º(éœ€è¦ç¿»å¢™ï¼Œæˆ–è€…æ­å»ºä»£ç†)
disqus:
  enable: false
  shortname: snippet
  count: false

### ç•…è¨€è¯„è®º(éœ€è¦ICPå¤‡æ¡ˆ)
changyan:
  enable: false
  appid:
  conf:

### Valineè¯„è®º å‚è€ƒç½‘ç«™: [valineè¯„è®º](https://valine.js.org/)
valine:
  enable: false
  appId: xOKV9J4UeQAtVkvnJC7Kq2Jn-gzGzoHsz
  appKey: erIpQac4azoCmgfBB7Dl9maa
  placeholder: è¯´ç‚¹ä»€ä¹ˆå§
  notify: false # é‚®ä»¶é€šçŸ¥
  verify: false # éªŒè¯ç 
  avatar: mm # avatarå¤´åƒ
  meta: nick,mail # è¾“å…¥æ¡†å†…å®¹ï¼Œå¯é€‰å€¼nick,mail,link
  pageSize: 10

## Gitalkè¯„è®º å‚è€ƒç½‘ç«™: [ä¸€ä¸ªåŸºäºGithub Issueå’ŒPreactå¼€å‘çš„è¯„è®ºæ’ä»¶](https://gitalk.github.io/)
gitalk:
   enable: false
   clientID: "" # Github åº”ç”¨ID
   clientSecret: "" # Github åº”ç”¨å¯†é’¥
   repo: shenliyang.github.io # Githubä»“åº“åœ°å€
   owner: shenliyang  # Github ç”¨æˆ·å(Githubä»“åº“æ‹¥æœ‰è€…)
   admin: shenliyang # GitHub repository çš„æ‰€æœ‰è€…å’Œåˆä½œè€… (å¯¹è¿™ä¸ª repository æœ‰å†™æƒé™çš„ç”¨æˆ·)å¯ä»¥æœ‰ä¸€ä¸ªæˆ–å¤šä¸ªï¼Œå¦‚æœæœ‰å¤šåå¯ä½¿ç”¨ï¼Œä¾‹å¦‚ï¼šadmin: admin1,admin2 é…ç½®
   perPage: 10 # æ¯æ¬¡åŠ è½½çš„æ•°æ®å¤§å°ï¼Œæœ€å¤š100
   distractionFreeMode: true # æ˜¯å¦å¯ç”¨æ— å¹²æ‰°æ¨¡å¼ï¼Œç±»ä¼¼Facebookè¯„è®ºæ¡†çš„å…¨å±é®ç½©æ•ˆæœ

   ## ä»¥ä¸‹å‚æ•°ä¸»é¢˜ä¼šé»˜è®¤å¤„ç†ï¼Œä¸éœ€è¦é…ç½®
   # language // è¯­è¨€ç±»å‹ï¼Œé»˜è®¤ä¸ºç«™ç‚¹é…ç½®ä¸­é€‰é¡¹
   # id // é¡µé¢çš„å”¯ä¸€æ ‡è¯†, å·²ä½¿ç”¨md5å¯¹pathnameè½¬æ¢ç”Ÿæˆå”¯ä¸€idå¤„ç†

## ç½‘ç«™è®¿å®¢ç»Ÿè®¡ [ä¸è’œå­ç»Ÿè®¡](http://busuanzi.ibruce.info/)
visit_counter:
   site: true # æ€»è®¿é—®é‡å’Œè®¿é—®äººæ•°ç»Ÿè®¡
   page: true # æ–‡ç« é˜…è¯»é‡ç»Ÿè®¡

## ç½‘ç«™è®¿é—®ç»Ÿè®¡åˆ†æ

### ç½‘ç›ŸCNZZç»Ÿè®¡
cnzz_analytics: 1263868967

### ç™¾åº¦ç»Ÿè®¡
baidu_analytics:

### è°·æ­Œç»Ÿè®¡
google_analytics:

### è…¾è®¯åˆ†æ
tencent_analytics:

### ç™¾åº¦ç«™ç‚¹è®¤è¯
baidu_site_verification:

### ç™¾åº¦è‡ªåŠ¨æ¨é€
baidu_push: true

#ç½‘ç«™ä¸»é¢˜é…ç½®
since: 2017
beian:
robot: 'all' ### æ§åˆ¶æœç´¢å¼•æ“çš„æŠ“å–å’Œç´¢å¼•ç¼–åˆ¶è¡Œä¸ºï¼Œé»˜è®¤ä¸ºall
version: 1.2.3